export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY_DETAIL = "FETCH_COUNTRY_DETAIL";
export const GET_COUNTRY_ERROR = "GET_COUNTRY_ERROR";
export const GET_COUNTRY_DETAILS_ERROR = "GET_COUNTRY_DETAILS_ERROR";
